title: Habit Tracker
remote_theme: just-the-docs/just-the-docs
mermaid:
  version: "10.9.0" # Pick version from https://cdn.jsdelivr.net/npm/mermaid/
callouts:
  tip:
    title: 🤍 Tip
    color: purple
  info:
    title: ℹ️ Info
    color: blue
  attention:
    title: ❕ Attention
    color: yellow
  download:
    title: 💾 Download
    color: grey-dk

collections:
  pages:
    output: true
    permalink: /:collection/:name/

just_the_docs:
  search_enabled: true
  show_last_updated_time: true
  show_last_updated_time_format: "%b %-d, %Y"
  collections:
    nav:
      - title: "Habit Tracker"
        url: "/Web_Anwendungen_Projekt/"
        children:
          - title: "Value Proposition"
            url: "/Web_Anwendungen_Projekt/value-proposition/"
          - title: "Technical Docs"
            url: "/Web_Anwendungen_Projekt/technical-docs/"
          - title: "Design Decisions"
            url: "/Web_Anwendungen_Projekt/design-decisions/"
          - title: "User Evaluation"
            url: "/Web_Anwendungen_Projekt/user-evaluation/"
          - title: "Team Evaluation"
            url: "/Web_Anwendungen_Projekt/team-evaluation/"

baseurl: "/Web_Anwendungen_Projekt"
url: "https://imaenkaa.github.io/Web_Anwendungen_Projekt/"

